---
title: "R in Production Part I: Challenges and Examples"
author: "Branden Collingsworth "
date: "2019/11/4"
output:
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts]
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

#Motivation

##You should learn how to get your R code into production

- all the value that you are ever going to create as a data scientist is going to happen when someone else makes a decision or when you automate the decision making process entirely 

- getting your work product into the hands of users or into another system should be a core competency

---
# How do I know I need it?

You have some code that does some work. 

Other people need this work done without your help.


---
# Production Challenges

* Infrastructure: A computer to run my code

* Source Control: The code itself 

* Testing: A way to tell if it’s working correctly when I’m not watching it 

---
# Signs You Have a Problem

* Runs on your laptop

* Code is not backed up, no version history 

* Don’t know what software/version your code needs to run

* You tell a user that “I don’t know, it runs on my machine”

* You need to manually intervene to get the code to run 

---
class: inverse

# R Programmers Can Do Production

## It's not that hard, using only<sup>1</sup> R 

.footnote[[1] Mostly R]


---
# What You Might Need to Learn

* Docker/Docker Host/Docker Hub basics

* Git/GitHub basics

* Linux command line basics


---
# Demos of Pure R Production Workloads

* [ETL Job](http://localhost:4200/ETL-demo.html)

* [Static Site](http://localhost:4200/)

* [API](http://localhost:8000/predict)

* Shiny Web App

---
# Bringing in Docker

* [Dockerfile](https://github.com/brandco/Rmisc/blob/master/RinProduction/Dockerfile)

* [Build Script](https://github.com/brandco/Rmisc/blob/master/RinProduction/build.r)

* Commands

.small[
```
docker build -t rprod .
docker run --name static -p 4200:4200 rprod
docker run --name api -p 8000:8000 -w /usr/src/app rprod Rscript predict-api.R
```]
---
#Cloud Deployment

Docker on my laptop is the same as other Docker hosts

1. Push image to repository

2. Create an App Service for the Docker container

3. Start it: https://rmd-server.azurewebsites.net/

---
# I Should Mention

* Security

* Secrets

* Performance

* Cost

* Testing and monitoring

---
# I Don’t Have to Mention

* Which web framework is the best?

* How much CSS, HTML and JavaScript you need to know?

* Who’s going to be your sysadmin?

---
# Recap of R packages featured

### Self-documenting ETL pipeline

* rmarkdown: Dynamic Documents for R

### Static website

* servr: A Simple HTTP Server to Serve Static Files or Dynamic Documents

### API

* plumber: An API Generator for R

### Dynamic Web Application

* shiny: Web Application Framework for R

### Docker Base Images Used in Demos

* [The Rocker Project: Docker Containers for the R Environment](https://www.rocker-project.org/)


---
class: center, inverse, middle

#Questions?